import { expect, test, type Page } from '@playwright/test'

const active = (page: Page) => page.locator('.markdown-body [contenteditable]:focus')
async function single(page: Page, source = '') {
  await page.goto('/')
  await page.locator('.cm-content').fill(source)
  await page.getByRole('button', { name: 'Single-page editing', exact: true }).click()
}
async function slash(page: Page, name: string) {
  await active(page).press('/')
  await page.getByRole('dialog', { name: 'Add content' }).getByRole('button', { name, exact: true }).click()
}

test('write from an empty page, split a paragraph, merge and keep the source hidden', async ({ page }) => {
  await single(page)
  await page.locator('.markdown-body [contenteditable]').fill('First paragraph')
  await active(page).press('End')
  await active(page).press('Enter')
  await active(page).fill('Second paragraph')
  await active(page).press('Home')
  await active(page).press('ArrowRight')
  await active(page).press('ArrowRight')
  await active(page).press('ArrowRight')
  await active(page).press('Enter')
  await expect(page.locator('.markdown-body > p')).toHaveText(['First paragraph', 'Sec', 'ond paragraph'])
  await active(page).press('Backspace')
  await expect(page.locator('.markdown-body > p')).toHaveText(['First paragraph', 'Second paragraph'])
  await expect(page.locator('.pane--editor')).toBeHidden()
  await expect(page.locator('.save-status')).toHaveText('Saved in this browser')
  await page.reload()
  await expect(page.locator('.markdown-body > p')).toHaveText(['First paragraph', 'Second paragraph'])
})

test('slash menu creates headings, lists and exits an empty list item', async ({ page }) => {
  await single(page)
  await page.locator('.markdown-body [contenteditable]').focus()
  await slash(page, 'Heading 2')
  await active(page).fill('Meeting notes')
  await active(page).press('End')
  await active(page).press('Enter')
  await slash(page, 'To-do list')
  await active(page).fill('First task')
  await active(page).press('End')
  await active(page).press('Enter')
  await active(page).fill('Second task')
  await active(page).press('End')
  await active(page).press('Enter')
  await active(page).press('Enter')
  await active(page).fill('After tasks')
  await expect(page.locator('.markdown-body h2')).toHaveText('Meeting notes')
  await expect(page.locator('.markdown-body li')).toHaveText(['First task', 'Second task'])
  await expect(page.locator('.markdown-body input[type=checkbox]')).toHaveCount(2)
  await page.locator('.markdown-body input[type=checkbox]').first().check()
  await expect(page.locator('.markdown-body > p').last()).toHaveText('After tasks')
  await expect(page.locator('.pane--editor')).toBeHidden()
  await expect(page.locator('.save-status')).toHaveText('Saved in this browser')
  await page.reload()
  await expect(page.locator('.markdown-body input[type=checkbox]').first()).toBeChecked()
  await expect(page.locator('.markdown-body input[type=checkbox]').last()).not.toBeChecked()
})

test('insert code and a table, preserve later content, and undo a deleted block', async ({ page }) => {
  const original = '# Title\n\nBefore.\n\nUntouched  **spacing**.\n\n[ref]: https://example.com\n'
  await single(page, original)
  await page.locator('.markdown-body > p').first().locator('[contenteditable]').focus()
  await page.locator('.preview-header').getByRole('button', { name: 'Add content', exact: true }).click()
  await page.getByRole('dialog', { name: 'Add content' }).getByRole('button', { name: 'Code block', exact: true }).click()
  await page.getByRole('textbox', { name: 'Code block', exact: true }).fill('const answer = 42;')
  await page.getByRole('textbox', { name: 'Code block', exact: true }).press('Escape')
  await page.locator('.preview-header').getByRole('button', { name: 'Add content', exact: true }).click()
  await page.getByRole('dialog', { name: 'Add content' }).getByRole('button', { name: 'Table', exact: true }).click()
  const table = page.getByRole('dialog', { name: 'Edit table', exact: true })
  await table.getByRole('textbox', { name: 'Row 1, column 1', exact: true }).fill('New entry')
  await table.getByRole('button', { name: 'Apply changes', exact: true }).click()
  await expect(page.locator('.markdown-body table')).toContainText('New entry')
  await page.locator('.markdown-body h1 [contenteditable]').focus()
  await page.locator('.preview-header').getByRole('button', { name: 'Add content', exact: true }).click()
  await page.getByRole('button', { name: 'Delete block', exact: true }).click()
  await expect(page.locator('.markdown-body h1')).toHaveCount(0)
  await page.getByRole('button', { name: 'Preview editing tools', exact: true }).click()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.locator('.markdown-body h1')).toHaveText('Title')
  await page.getByRole('button', { name: 'Split editing', exact: true }).click()
  await expect(page.locator('.cm-content')).toContainText('Untouched  **spacing**.')
  await expect(page.locator('.cm-content')).toContainText('[ref]: https://example.com')
})

test('mobile can append and choose a block without opening the source', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 })
  await page.goto('/')
  await page.locator('.cm-content').fill('# Mobile\n')
  await page.getByRole('tab', { name: 'Preview', exact: true }).click()
  await page.locator('.markdown-append').getByRole('button', { name: 'Add content' }).click()
  await slash(page, 'Bulleted list')
  await active(page).fill('Mobile entry')
  await expect(page.locator('.markdown-body li')).toHaveText('Mobile entry')
  await expect(page.locator('.pane--editor')).toBeHidden()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('quote, numbered list and divider keep a usable next writing position', async ({ page }) => {
  await single(page)
  await page.locator('.markdown-body [contenteditable]').focus()
  await slash(page, 'Quote')
  await active(page).fill('A new quote')
  await expect(page.locator('.markdown-body blockquote')).toHaveText('A new quote')
  await active(page).press('End')
  await active(page).press('Enter')
  await active(page).press('Enter')
  await slash(page, 'Numbered list')
  await active(page).fill('One')
  await active(page).press('End')
  await active(page).press('Enter')
  await active(page).fill('Two')
  await expect(page.locator('.markdown-body ol li')).toHaveText(['One', 'Two'])
  await page.locator('.markdown-append button').click()
  await slash(page, 'Divider')
  await active(page).fill('After the divider')
  await expect(page.locator('.markdown-body hr')).toHaveCount(1)
  await expect(page.locator('.markdown-body > p').last()).toHaveText('After the divider')
  await expect(page.locator('.save-status')).toHaveText('Saved in this browser')
  await page.reload()
  await expect(page.locator('.markdown-body blockquote')).toHaveText('A new quote')
  await expect(page.locator('.markdown-body ol li')).toHaveText(['One', 'Two'])
  await expect(page.locator('.markdown-body hr')).toHaveCount(1)
})

test('choosing a block on an empty list item preserves the other items', async ({ page }) => {
  await single(page, '- Keep this\n- Keep this too\n')
  await page.locator('.markdown-body li').last().locator('[contenteditable]').focus()
  await active(page).press('End')
  await active(page).press('Enter')
  await slash(page, 'Heading 2')
  await active(page).fill('Following section')
  await expect(page.locator('.markdown-body li')).toHaveText(['Keep this', 'Keep this too'])
  await expect(page.locator('.markdown-body h2')).toHaveText('Following section')
})
