import { expect, test, type Page } from '@playwright/test'

const source = (page: Page) => page.locator('.editor-host .cm-line').allTextContents().then((lines) => lines.join('\n'))
const toggle = (page: Page) => page.getByRole('button', { name: 'Live editing', exact: true })

test('editing rendered blocks preserves source, selection, undo, and recovery across layouts', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  const original = '# Same place\n\nA **bold** word and [link][ref].  \nNext line.\n\n## Details\n\nKeep `code` and <literal>.\n\n[ref]: https://example.com\n'
  await page.locator('.cm-content').fill(original)
  await page.keyboard.press('Control+Home')
  await page.keyboard.press('End')
  await toggle(page).click()
  await expect(page.locator('.live-preview-block h1')).toHaveText('Same place')
  await expect(page.locator('.pane--preview')).toHaveCount(0)
  await expect(page.locator('.live-preview-block strong')).toHaveText('bold')
  await expect(page.locator('.live-preview-block a')).toHaveAttribute('href', 'https://example.com')
  // Switching the presentation keeps the previous insertion point.
  await page.locator('.cm-content').focus()
  await page.keyboard.type(' edited')
  await page.locator('.live-editing-hint').click()
  await expect(page.locator('.live-preview-block h1')).toHaveText('Same place edited')
  await toggle(page).click()
  await expect.poll(() => source(page)).toBe(original.replace('Same place', 'Same place edited'))
  await page.locator('.cm-content').focus()
  await page.keyboard.press('Control+z')
  await expect.poll(() => source(page)).toBe(original)
  await toggle(page).click()
  const paragraph = page.locator('.live-preview-block p').filter({ hasText: 'A bold word' })
  await paragraph.click()
  await expect(page.locator('.live-source-line').first()).toContainText('A **bold** word')
  await page.keyboard.press('End')
  await page.keyboard.type(' Changed.')
  await page.locator('.live-editing-hint').click()
  await expect(paragraph).toContainText('Changed.')
  await expect(page.locator('.save-status')).toHaveText('Saved in this browser')
  await page.reload()
  await expect(toggle(page)).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.live-preview-block p').filter({ hasText: 'Changed.' })).toBeVisible()
  await toggle(page).click()
  await expect.poll(() => source(page)).toContain('[ref]: https://example.com\n')
  await expect.poll(() => source(page)).toContain('Keep `code` and <literal>.')
  expect(errors).toEqual([])
})

test('live checkboxes and the existing table editor change the same Markdown document', async ({ page }) => {
  await page.goto('/')
  const original = '# Tasks\n\n- [ ] First\n- [x] Second\n\n| Item | State |\n| --- | --- |\n| Table | Open |\n\nKeep this paragraph.'
  await page.locator('.cm-content').fill(original)
  await toggle(page).click()
  const first = page.locator('.live-preview-block input[type=checkbox]').first()
  await first.check()
  await expect(first).toBeChecked()
  await toggle(page).click()
  await expect.poll(() => source(page)).toBe(original.replace('- [ ] First', '- [x] First'))
  await page.locator('.cm-content').focus()
  await page.keyboard.press('Control+z')
  await expect.poll(() => source(page)).toBe(original)
  await toggle(page).click()
  await page.locator('.live-preview-block').getByRole('button', { name: 'Edit table', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Edit table', exact: true })
  await dialog.getByRole('textbox', { name: 'Row 1, column 2', exact: true }).fill('Done')
  await dialog.getByRole('button', { name: 'Apply changes', exact: true }).click()
  await page.locator('.live-editing-hint').click()
  await expect(page.locator('.live-preview-block table')).toContainText('Done')
  await toggle(page).click()
  await expect.poll(() => source(page)).toContain('| Table | Done |')
  await page.locator('.cm-content').focus()
  await page.keyboard.press('Control+z')
  await expect.poll(() => source(page)).toBe(original)
})

test('diagrams, math, footnotes, missing assets, and source downloads remain honest', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  const original = '# Rich content\n\nFormula $x^2$ and note[^one].\n\n```mermaid\ngraph LR\n A[Start] --> B[Done]\n```\n\n![Missing image](./assets/missing.png)\n\n---\n\n[^one]: Keep **this note**.\n'
  await page.locator('.cm-content').fill(original)
  await toggle(page).click()
  await expect(page.locator('.live-preview-block .mermaid-block svg')).toBeVisible()
  await expect(page.locator('.live-preview-block .katex')).toHaveCount(1)
  await expect(page.locator('.live-preview-block .footnotes')).toContainText('Keep this note.')
  await expect(page.locator('.live-preview-block img')).toHaveClass(/is-missing/)
  await expect(page.locator('.live-preview-block hr')).toHaveCount(1)
  await page.getByRole('button', { name: 'Export', exact: true }).click()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Markdown Keep the editable source', exact: true }).click()
  const stream = await (await downloadPromise).createReadStream()
  const chunks: Buffer[] = []
  for await (const chunk of stream!) chunks.push(Buffer.from(chunk))
  expect(Buffer.concat(chunks).toString()).toBe(original)
  expect(errors).toEqual([])
})

test('keyboard block editing, find, slash commands, and document modes remain usable', async ({ page }) => {
  await page.goto('/')
  const original = '# Keyboard\n\n## Target\n\nText\n\n'
  await page.locator('.cm-content').fill(original)
  await toggle(page).click()
  const heading = page.locator('.live-preview-block').filter({ has: page.locator('h2') })
  await heading.focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('.cm-content')).toBeFocused()
  await expect(page.locator('.live-source-line')).toHaveText('## Target')
  await page.keyboard.press('End')
  await page.keyboard.type(' edited')
  await page.getByRole('button', { name: 'Search document', exact: true }).click()
  const search = page.locator('.cm-search input[name=search]')
  await search.pressSequentially('Text')
  await page.keyboard.press('Enter')
  await page.keyboard.press('Escape')
  await expect(page.locator('.live-source-line')).toContainText('Text')
  await page.locator('.cm-content').focus()
  await page.keyboard.press('Control+End')
  await page.keyboard.press('/')
  await expect(page.getByRole('textbox', { name: 'Search commands', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('combobox', { name: 'Document mode', exact: true }).selectOption('text')
  await expect(toggle(page)).toHaveCount(0)
  await expect(page.locator('.pane--preview')).toBeVisible()
  await expect.poll(() => source(page)).toBe(original.replace('## Target', '## Target edited'))
  await page.getByRole('combobox', { name: 'Document mode', exact: true }).selectOption('markdown')
  await expect(toggle(page)).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.live-preview-block h2')).toHaveText('Target edited')
})

test('local images resolve after import and stay available when switching views', async ({ page }) => {
  await page.goto('/')
  await page.locator('.cm-content').fill('# Images\n\n![Photo](./assets/photo.png)\n\n')
  await toggle(page).click()
  await expect(page.locator('.live-preview-block img')).toHaveClass(/is-missing/)
  await page.locator('input[type=file]').nth(1).setInputFiles({
    name: 'photo.png', mimeType: 'image/png',
    buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jF9sAAAAASUVORK5CYII=', 'base64'),
  })
  await expect(page.locator('.asset-trigger small')).toHaveText('1')
  await page.locator('.live-editing-hint').click()
  const image = page.locator('.live-preview-block img').first()
  await expect(image).toHaveClass(/is-resolved/)
  await expect.poll(() => image.evaluate((element: HTMLImageElement) => element.naturalWidth)).toBe(1)
  await toggle(page).click()
  await expect(page.locator('.pane--preview img').first()).toHaveClass(/is-resolved/)
  await toggle(page).click()
  await expect.poll(() => image.evaluate((element: HTMLImageElement) => element.naturalWidth)).toBe(1)
})

test('list editing, selections spanning blocks, and an empty live document remain editable', async ({ page }) => {
  await page.goto('/')
  const original = '# Lists\n\n1. First\n2. Second\n\n## After\n\nKeep this.'
  await page.locator('.cm-content').fill(original)
  await toggle(page).click()
  await page.locator('.live-preview-block li').first().click()
  await page.keyboard.press('End')
  await page.keyboard.press('Enter')
  await expect(page.locator('.live-source-line')).toContainText(['1. First', '2. ', '3. Second'])
  await page.keyboard.press('Control+z')
  await page.keyboard.press('Control+a')
  await expect(page.locator('.live-preview-block')).toHaveCount(0)
  await expect.poll(() => source(page)).toBe(original)
  await page.keyboard.press('Backspace')
  await expect.poll(() => source(page)).toBe('')
  await page.keyboard.type('# New document')
  await page.locator('.live-editing-hint').click()
  await expect(page.locator('.live-preview-block h1')).toHaveText('New document')
})

test.describe('touch editing', () => {
  test.use({ hasTouch: true })

  test('the live editor fits a phone and shares theme and font settings', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 812 })
    await page.goto('/')
    await page.locator('.cm-content').fill('# Mobile\n\nA **readable** paragraph.\n\n## Next\n\nAnother block.')
    await toggle(page).click()
    await expect(page.locator('.mobile-view-tabs')).toBeHidden()
    await expect(page.locator('.cm-content')).toBeVisible()
    await page.getByRole('button', { name: 'Preview theme: Light', exact: true }).click()
    await page.getByRole('button', { name: /^Dark Balanced/ }).click()
    await expect(page.locator('.editor-host')).toHaveClass(/theme-dark/)
    await page.getByRole('button', { name: 'Font size settings', exact: true }).click()
    await page.locator('#markdown-font-size').fill('22')
    await page.keyboard.press('Escape')
    await expect(page.locator('.editor-host .cm-scroller')).toHaveCSS('font-size', '22px')
    await page.locator('.live-preview-block h1').tap()
    await expect(page.locator('.cm-content')).toBeFocused()
    await expect(page.locator('.live-source-line span').first()).toHaveCSS('color', 'rgb(229, 234, 242)')
    await page.keyboard.press('End')
    await page.keyboard.type(' edit')
    await page.locator('.live-editing-hint').click()
    await expect(page.locator('.live-preview-block h1')).toHaveText('Mobile edit')
    await page.getByRole('button', { name: 'Switch to Traditional Chinese', exact: true }).click()
    await expect(page.getByRole('button', { name: '即時編輯', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.setViewportSize({ width: 812, height: 375 })
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.getByRole('button', { name: '即時編輯', exact: true }).click()
    await expect(page.locator('.cm-content')).toBeVisible()
  })
})
