import { expect, test, type Page } from '@playwright/test'

const preview = (page: Page) => page.locator('.pane--preview .markdown-body')
const text = '[data-markdown-edit-text]'

async function start(page: Page, source: string) {
  await page.goto('/')
  await page.locator('.cm-content').fill(source)
}

async function download(page: Page) {
  await page.getByRole('button', { name: 'Export', exact: true }).click()
  const pending = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Markdown Keep the editable source', exact: true }).click()
  const stream = await (await pending).createReadStream()
  const chunks: Buffer[] = []
  for await (const chunk of stream!) chunks.push(Buffer.from(chunk))
  return Buffer.concat(chunks).toString()
}

test('direct typing preserves formatting, other source blocks, save, undo and redo', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  const source = '# Original\n\nA **bold** word and _italic_ text.\n\n```js\nconst exact = 1;\n```\n\nUntouched  spacing.\n'
  await start(page, source)
  await expect(page.getByRole('button', { name: 'Edit preview', exact: true })).toHaveCount(0)
  const heading = preview(page).locator(`h1 ${text}`)
  await heading.click()
  await page.keyboard.press('Control+a')
  await page.keyboard.type('Changed by typing')
  await page.keyboard.press('Enter')
  await expect(heading).toHaveText('Changed by typing')
  await preview(page).locator(`strong ${text}`).fill('stronger')
  await expect(preview(page).locator('em')).toHaveText('italic')
  const changed = await download(page)
  expect(changed).toContain('# Changed by typing')
  expect(changed).toContain('**stronger**')
  expect(changed).toContain('```js\nconst exact = 1;\n```\n\nUntouched  spacing.\n')
  expect(changed).not.toMatch(/contenteditable|markword-md-text/)
  await page.getByRole('button', { name: 'Preview editing tools', exact: true }).click()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(preview(page).locator('strong')).toHaveText('bold')
  await page.getByRole('button', { name: 'Preview editing tools', exact: true }).click()
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await expect(preview(page).locator('strong')).toHaveText('stronger')
  await expect(page.locator('.save-status')).toHaveText('Saved in this browser')
  await page.reload()
  await expect(preview(page).locator('h1')).toHaveText('Changed by typing')
  await expect(preview(page).locator('strong')).toHaveText('stronger')
  await expect(heading).toHaveAttribute('contenteditable', 'plaintext-only')
  expect(errors).toEqual([])
})

test('link edits are validated and source-only view can be hidden without losing undo', async ({ page }) => {
  await start(page, '# Links\n\nVisit [our **site**][ref].\n\n[ref]: https://example.com/old "A title"\n')
  await page.getByRole('button', { name: 'Single-page editing', exact: true }).click()
  await expect(page.locator('.pane--editor')).toBeHidden()
  await preview(page).getByRole('link').click()
  await page.getByLabel('Link address', { exact: true }).fill('javascript:alert(1)')
  await page.getByRole('button', { name: 'Apply changes', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Enter a valid address')
  await page.getByLabel('Link address', { exact: true }).fill('https://example.com/new?q=1&v=2')
  await page.getByRole('button', { name: 'Apply changes', exact: true }).click()
  await expect(preview(page).getByRole('link')).toHaveAttribute('href', 'https://example.com/new?q=1&v=2')
  expect(page.url()).not.toContain('example.com')
  await page.getByRole('button', { name: 'Preview editing tools', exact: true }).click()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(preview(page).getByRole('link')).toHaveAttribute('href', 'https://example.com/old')
  await page.getByRole('button', { name: 'Preview editing tools', exact: true }).click()
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await page.getByRole('button', { name: 'Split editing', exact: true }).click()
  expect(await download(page)).toContain('[our **site**](https://example.com/new?q=1&v=2 "A title")')
})

test('nested lists, task checkboxes and blockquotes retain structure', async ({ page }) => {
  await start(page, '# Lists\n\n- [ ] First **task**\n- [x] Second\n  - Nested\n\n> Quoted **idea**.\n\nAfter.\n')
  await preview(page).locator(`li ${text}`).filter({ hasText: /^First / }).fill('Updated ')
  await preview(page).locator('input[type=checkbox]').first().check()
  await preview(page).locator(`li ${text}`).filter({ hasText: /^Nested$/ }).fill('Nested item')
  await preview(page).locator(`blockquote strong ${text}`).fill('thought')
  const result = await download(page)
  expect(result).toContain('[x] Updated **task**')
  expect(result).toContain('Nested item')
  expect(result).toContain('> Quoted **thought**.')
  expect(result).toContain('\n\nAfter.\n')
  await expect(page.locator('.save-status')).toHaveText('Saved in this browser')
  await page.reload()
  await expect(preview(page).locator('ul ul li')).toHaveText('Nested item')
  await expect(preview(page).locator('input[type=checkbox]').first()).toBeChecked()
})

test('typed markup stays literal, IME Enter keeps focus, and source changes rebuild editing', async ({ page }) => {
  await start(page, '# Original\n\nText.\n')
  const heading = preview(page).locator(`h1 ${text}`)
  await heading.fill('*literal* ~~keep~~ [text] $x$ <img src=x onerror=alert(1)>')
  await heading.dispatchEvent('keydown', { key: 'Enter', isComposing: true })
  await expect(heading).toBeFocused()
  await expect(page.locator('.save-status')).toHaveText('Saved in this browser')
  await page.reload()
  await expect(preview(page).locator('h1')).toHaveText('*literal* ~~keep~~ [text] $x$ <img src=x onerror=alert(1)>')
  await expect(preview(page).locator('h1 img, h1 em, h1 del, h1 .katex')).toHaveCount(0)
  await page.locator('.cm-content').fill('# Replaced from source\n\nNew text.\n')
  await expect(heading).toHaveText('Replaced from source')
  await heading.fill('Another edit')
  expect(await download(page)).toBe('# Another edit\n\nNew text.\n')
})

test('tables remain editable after preceding block length changes, protected content stays intact', async ({ page }) => {
  const tail = '| Column | State |\n| --- | --- |\n| Item | Open |\n\nFormula $x^2$ and note[^one].\n\n```mermaid\ngraph LR\n A --> B\n```\n\n[^one]: Keep this note.\n'
  await start(page, '# Heading\n\nA paragraph.\nAnother line.\n\n' + tail)
  await preview(page).locator(`p ${text}`).filter({ hasText: 'A paragraph.' }).fill('Shorter paragraph.')
  await page.getByRole('button', { name: 'Single-page editing', exact: true }).click()
  await preview(page).getByRole('button', { name: 'Edit table 1', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Edit table', exact: true })
  await expect(dialog).toBeVisible()
  await dialog.getByRole('textbox', { name: 'Row 1, column 2', exact: true }).fill('Done')
  await dialog.getByRole('button', { name: 'Apply changes', exact: true }).click()
  await expect(preview(page).locator('table')).toContainText('Done')
  expect(await download(page)).toContain(tail.replace('| Item | Open |', '| Item | Done |'))
  await expect(preview(page).locator('.katex')).toHaveCount(1)
  await expect(preview(page).locator('.mermaid-image')).toBeVisible()
})

test('empty documents can be written visually and edits work on mobile without overflow', async ({ page }) => {
  await start(page, '')
  await preview(page).locator(text).fill('Start here')
  expect(await download(page)).toBe('Start here')
  await page.setViewportSize({ width: 375, height: 812 })
  await page.getByRole('tab', { name: 'Preview', exact: true }).click()
  await preview(page).locator(text).fill('Edited on mobile')
  await page.getByRole('tab', { name: 'Editor', exact: true }).click()
  await expect(page.locator('.cm-content')).toHaveText('Edited on mobile')
  await page.getByRole('tab', { name: 'Preview', exact: true }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await expect(preview(page).locator(text)).toHaveText('Edited on mobile')
})

test('hidden reference definitions survive, and switching modes restores editable preview', async ({ page }) => {
  const original = '# Title\n\n> [ref]: https://example.com\n>\n> Keep this definition.\n\nRead [this][ref].\n\n| A | B |\n| --- | --- |\n| One | Two |\n\nMath $x^2$.\n'
  await start(page, original)
  await expect(preview(page).locator(`blockquote ${text}`)).toHaveCount(0)
  await preview(page).locator(`h1 ${text}`).fill('New title')
  await preview(page).locator(`h1 ${text}`).press('Control+z')
  await expect(preview(page).locator('h1')).toHaveText('Title')
  await page.getByRole('button', { name: 'Preview editing tools', exact: true }).click()
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await expect(preview(page).locator('h1')).toHaveText('New title')
  expect(await download(page)).toBe(original.replace('# Title', '# New title'))
  for (let index = 0; index < 2; index++) {
    await page.getByLabel('Document mode', { exact: true }).selectOption('text')
    await expect(preview(page).locator(text)).toHaveCount(0)
    await page.getByLabel('Document mode', { exact: true }).selectOption('markdown')
    await expect(preview(page).locator(`h1 ${text}`)).toHaveAttribute('contenteditable', 'plaintext-only')
    await expect(preview(page).getByRole('button', { name: 'Edit table 1', exact: true })).toBeVisible()
    await expect(preview(page).locator('.katex')).toHaveCount(1)
    await expect(preview(page).getByRole('link')).toHaveAttribute('href', 'https://example.com')
  }
})

test('preview editing, tools and links keep both content areas aligned', async ({ page }) => {
  await page.setViewportSize({ width: 1600, height: 1000 })
  await page.goto('/')
  await page.locator('.cm-content').fill('* **Market Data**\n\n  * 歷史 Tick 載入\n  * [即時 Tick 接收](https://example.com)\n')
  await expect(preview(page).getByRole('link')).toBeVisible()
  const sourceBounds = (await page.locator('.editor-host').boundingBox())!
  const previewBounds = await page.locator('.preview-scroll').boundingBox()
  expect(previewBounds!.y).toBe(sourceBounds.y)
  expect(previewBounds!.height).toBe(sourceBounds.height)
  const firstText = await preview(page).locator('strong').boundingBox()
  const firstSourceLine = (await page.locator('.cm-line').first().boundingBox())!
  expect(Math.abs(firstText!.y - firstSourceLine.y)).toBeLessThan(4)
  await page.getByRole('button', { name: 'Preview editing tools', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Undo', exact: true })).toBeVisible()
  expect(await page.locator('.preview-scroll').boundingBox()).toEqual(previewBounds)
  expect(await preview(page).locator('strong').boundingBox()).toEqual(firstText)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'Preview editing tools', exact: true })).toBeFocused()
  await preview(page).getByRole('link').click()
  await page.getByLabel('Link address', { exact: true }).focus()
  expect(await page.locator('.preview-scroll').boundingBox()).toEqual(previewBounds)
  expect(await preview(page).locator('strong').boundingBox()).toEqual(firstText)
  await page.keyboard.press('Escape')
  await expect(page.locator('.markdown-link-form')).toHaveCount(0)
  await expect(preview(page).getByRole('link')).toBeFocused()
})

test('code editing preserves multiline input, fence safety, metadata and later blocks', async ({ page }) => {
  const original = '# Code\n\n```js title="example"\nconst original = 1;\n```\n\nUntouched **after**.\n\n| A | B |\n| --- | --- |\n| One | Two |\n'
  await start(page, original)
  const renderedCode = preview(page).getByRole('button', { name: 'Code block', exact: true })
  await renderedCode.click()
  const code = preview(page).getByRole('textbox', { name: 'Code block', exact: true })
  await code.fill('const value = 2;')
  await code.press('End')
  await code.press('Enter')
  await page.keyboard.insertText('console.log(value);')
  await code.press('Enter')
  await page.keyboard.insertText('```')
  await code.press('Control+Enter')
  await expect(code).toHaveCount(0)
  await expect(renderedCode.locator('.hljs-keyword').first()).toBeVisible()
  const changed = await download(page)
  expect(changed).toBe(original.replace('```js title="example"\nconst original = 1;\n```', '````js title="example"\nconst value = 2;\nconsole.log(value);\n```\n````'))
  await page.getByRole('button', { name: 'Preview editing tools', exact: true }).click()
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(renderedCode).not.toContainText('```')
  await page.getByRole('button', { name: 'Preview editing tools', exact: true }).click()
  await page.getByRole('button', { name: 'Redo', exact: true }).click()
  await expect(renderedCode).toContainText('console.log(value);')
  expect(await download(page)).toBe(changed)
  await preview(page).getByRole('button', { name: 'Edit table 1', exact: true }).click()
  await page.getByRole('textbox', { name: 'Row 1, column 2', exact: true }).fill('Edited')
  await page.getByRole('button', { name: 'Apply changes', exact: true }).click()
  expect(await download(page)).toBe(changed.replace('| One | Two |', '| One | Edited |'))
  await expect(page.locator('.save-status')).toHaveText('Saved in this browser')
  await page.reload()
  await expect(renderedCode).toHaveText('const value = 2;\nconsole.log(value);\n```\n')
})

test('empty and nested code blocks accept literal text without creating HTML or Markdown', async ({ page }) => {
  await start(page, '# Code\n\n~~~html\nold\n~~~\n\n> ```js\n> let n = 1;\n> ```\n\nAfter.\n')
  const renderedCodes = preview(page).getByRole('button', { name: 'Code block', exact: true })
  const code = preview(page).getByRole('textbox', { name: 'Code block', exact: true })
  await renderedCodes.first().click()
  await code.fill('')
  await code.press('Escape')
  await renderedCodes.first().click()
  await code.fill('<img src=x onerror=alert(1)>\n**literal**\n\nlast line\n')
  await code.press('Escape')
  await expect(renderedCodes.first().locator('img, strong')).toHaveCount(0)
  await renderedCodes.nth(1).click()
  await code.fill('let n = 2;\nconsole.log(n);')
  const result = await download(page)
  expect(result).toContain('~~~html\n<img src=x onerror=alert(1)>\n**literal**\n\nlast line\n~~~')
  expect(result).toContain('> ```js\n> let n = 2;\n> console.log(n);\n> ```')
  expect(result).toContain('\n\nAfter.\n')
  expect(result).not.toMatch(/contenteditable|Copy code/)
})
