import { expect, test, type Page } from '@playwright/test'

const openSettings = (page: Page) => page.getByRole('button', { name: 'Keyboard shortcuts', exact: true }).click()
const record = async (page: Page, action: string, keys: string) => {
  await page.getByRole('button', { name: `Set shortcut: ${action}`, exact: true }).click()
  await page.keyboard.press(keys)
}
const source = (page: Page) => page.locator('.cm-line').allTextContents().then((lines) => lines.join('\n'))

test('custom bindings persist and command hints follow changes, clearing, and reset', async ({ page }) => {
  await page.goto('/')
  await openSettings(page)
  await record(page, 'Open command palette', 'Control+Shift+k')
  await expect(page.locator('#shortcut-feedback')).toHaveText('Shortcut saved in this browser.')
  await page.keyboard.press('Escape')
  await expect(page.locator('.utility-command kbd')).toHaveText('Ctrl + Shift + K')
  await page.keyboard.press('Control+k')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.keyboard.press('Control+Shift+k')
  await expect(page.getByRole('textbox', { name: 'Search commands', exact: true })).toBeFocused()
  await expect(page.locator('.command-palette__list button').filter({ hasText: 'Search document' }).locator('kbd')).toHaveText('Ctrl + F')
  await page.keyboard.press('Escape')
  await page.reload()
  await expect(page.locator('.utility-command kbd')).toHaveText('Ctrl + Shift + K')
  await page.keyboard.press('Control+Shift+k')
  await expect(page.getByRole('dialog', { name: 'Command palette' })).toBeVisible()
  await page.keyboard.press('Escape')
  await openSettings(page)
  await page.getByRole('button', { name: 'Clear shortcut: Open command palette', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Set shortcut: Open command palette', exact: true })).toHaveText('Not assigned')
  await page.keyboard.press('Escape')
  await page.keyboard.press('Control+Shift+k')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('.utility-command kbd')).toHaveCount(0)
  await openSettings(page)
  await page.getByRole('button', { name: 'Restore defaults', exact: true }).click()
  await expect(page.locator('#shortcut-feedback')).toHaveText('Default shortcuts restored.')
  await page.keyboard.press('Escape')
  await page.keyboard.press('Control+k')
  await expect(page.getByRole('dialog', { name: 'Command palette' })).toBeVisible()
})

test('conflicts, editing keys, cancellation, and dialogs do not trigger commands while recording', async ({ page }) => {
  await page.goto('/')
  await openSettings(page)
  await record(page, 'Search document', 'Control+k')
  await expect(page.locator('#shortcut-feedback')).toHaveText('Already used by Open command palette. Clear that shortcut first.')
  await expect(page.getByRole('dialog', { name: 'Command palette' })).toHaveCount(0)
  await page.keyboard.press('Control+z')
  await expect(page.locator('#shortcut-feedback')).toHaveText('This shortcut is reserved for the browser or basic editing. Choose another.')
  await page.keyboard.press('x')
  await expect(page.locator('#shortcut-feedback')).toHaveText('Include Ctrl or Cmd and a letter, number, or punctuation key.')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: 'Keyboard shortcuts', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Set shortcut: Search document', exact: true })).toHaveText('Ctrl + F')
  await record(page, 'Search document', 'Tab')
  await expect(page.getByRole('button', { name: 'Clear shortcut: Search document', exact: true })).toBeFocused()
  await page.keyboard.press('Escape')
  await page.locator('.cm-content').fill('文字')
  await page.keyboard.press('Control+End')
  await page.keyboard.type('?')
  await expect.poll(() => source(page)).toBe('文字?')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.keyboard.press('Control+z')
  await expect.poll(() => source(page)).toBe('文字')
  await page.getByRole('button', { name: 'Keyboard shortcuts', exact: true }).focus()
  await page.keyboard.press('?')
  await expect(page.getByRole('dialog', { name: 'Keyboard shortcuts', exact: true })).toBeVisible()
})

test('search can move to another key and an unassigned command can use its old key', async ({ page }) => {
  await page.goto('/')
  await openSettings(page)
  await record(page, 'Search document', 'Control+Shift+g')
  await record(page, 'Insert: Heading 2', 'Control+f')
  await page.keyboard.press('Escape')
  await page.locator('.cm-content').fill('A note')
  await page.keyboard.press('Control+End')
  await page.keyboard.press('Control+f')
  await expect.poll(() => source(page)).toBe('A note\n## Heading\n')
  await expect(page.locator('.cm-search')).toHaveCount(0)
  await page.keyboard.press('Control+Shift+g')
  await expect(page.locator('.cm-search input').first()).toBeFocused()
  await page.keyboard.press('Escape')
  await page.keyboard.press('Control+k')
  await expect(page.locator('.command-palette__list button').filter({ hasText: 'Search document' }).locator('kbd')).toHaveText('Ctrl + Shift + G')
  await page.keyboard.press('Escape')
  await page.reload()
  await expect(page.locator('.cm-content')).toBeVisible()
  await page.keyboard.press('Control+Shift+g')
  await expect(page.locator('.cm-search')).toBeVisible()
})

test('clearing search disables its default binding without affecting normal typing', async ({ page }) => {
  await page.goto('/')
  await openSettings(page)
  await page.getByRole('button', { name: 'Clear shortcut: Search document', exact: true }).click()
  await page.keyboard.press('Escape')
  await page.locator('.cm-content').fill('A note')
  await page.keyboard.press('Control+End')
  await page.keyboard.press('Control+f')
  await expect(page.locator('.cm-search')).toHaveCount(0)
  await page.keyboard.type('!')
  await expect.poll(() => source(page)).toBe('A note!')
})

test('saving failures keep the prior shortcut and show an honest error', async ({ page }) => {
  await page.goto('/')
  await openSettings(page)
  await page.evaluate(() => {
    const save = Storage.prototype.setItem
    Storage.prototype.setItem = function (key, value) {
      if (key === 'markword.preference.shortcuts') throw new DOMException('Storage full', 'QuotaExceededError')
      save.call(this, key, value)
    }
  })
  await record(page, 'Open command palette', 'Control+Shift+k')
  await expect(page.locator('#shortcut-feedback')).toHaveText('Could not save shortcuts. Your settings are unchanged.')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'Set shortcut: Open command palette', exact: true })).toHaveText('Ctrl + K')
  await page.keyboard.press('Escape')
  await page.keyboard.press('Control+k')
  await expect(page.getByRole('dialog', { name: 'Command palette' })).toBeVisible()
})

test('mobile shortcut settings fit, scroll, and keep the footer reachable', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 })
  await page.goto('/')
  await openSettings(page)
  await page.getByRole('button', { name: 'Set shortcut: Show keyboard shortcuts', exact: true }).scrollIntoViewIfNeeded()
  await expect(page.getByRole('button', { name: 'Restore defaults', exact: true })).toBeInViewport()
  const fits = () => page.locator('.shortcut-help').evaluate((element) => {
    const rect = element.getBoundingClientRect()
    return rect.left >= 0 && rect.right <= innerWidth && rect.top >= 0 && rect.bottom <= innerHeight && element.scrollWidth <= element.clientWidth
  })
  expect(await fits()).toBe(true)
  await page.setViewportSize({ width: 812, height: 375 })
  await expect.poll(fits).toBe(true)
})
