import { expect, test } from '@playwright/test'

test('editing, appearance, recovery, and downloads keep the same document', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/')
  await expect(page).toHaveTitle('Markword')
  const document = '# Workspace check\n\nA document worth keeping.\n\n## Next step\n\nWrite something clear.'
  await page.locator('.cm-content').fill(document)
  await expect(page.locator('.markdown-body h1')).toHaveText('Workspace check')
  await expect(page.locator('.document-heading')).toContainText('Workspace check')
  await expect(page.locator('.save-status')).toHaveText('Saved in this browser')
  await page.reload()
  await expect(page.locator('.cm-content')).toContainText('A document worth keeping.')

  await page.getByRole('button', { name: 'Preview theme: Light', exact: true }).click()
  await page.getByRole('button', { name: /^Dark Balanced/ }).click()
  await expect(page.locator('.markdown-body')).toHaveClass(/theme-dark/)
  await page.getByRole('button', { name: 'Font size settings', exact: true }).click()
  await page.locator('#markdown-font-size').fill('22')
  await expect(page.locator('.markdown-body')).toHaveCSS('font-size', '22px')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: 'Font size settings', exact: true })).toBeFocused()

  await page.getByRole('button', { name: 'Revision history', exact: true }).click()
  await page.getByRole('button', { name: 'Create current revision', exact: true }).click()
  await expect(page.locator('.revision-panel__message')).toHaveText('Current revision created')
  await page.keyboard.press('Escape')
  await page.locator('.cm-content').fill('# Changed draft')
  await page.getByRole('button', { name: 'Revision history', exact: true }).click()
  await page.getByRole('button', { name: 'Restore this revision', exact: true }).click()
  await expect(page.locator('.revision-panel__message')).toContainText('previous content was backed up')
  await page.keyboard.press('Escape')
  await expect(page.locator('.markdown-body h1')).toHaveText('Workspace check')

  await page.getByRole('button', { name: 'Export', exact: true }).click()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Markdown Keep the editable source', exact: true }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('Workspace check.md')
  const stream = await download.createReadStream()
  const chunks: Buffer[] = []
  for await (const chunk of stream!) chunks.push(Buffer.from(chunk))
  expect(Buffer.concat(chunks).toString()).toBe(document)
  expect(errors).toEqual([])
})

test('keyboard controls, native dialogs, and resizing remain usable', async ({ page }) => {
  await page.goto('/')
  const splitter = page.getByRole('button', { name: 'Resize editor and preview', exact: true })
  const before = await page.locator('.pane--editor').boundingBox()
  await splitter.focus()
  await page.keyboard.press('ArrowRight')
  expect((await page.locator('.pane--editor').boundingBox())!.width).toBeGreaterThan(before!.width)
  const grip = (await splitter.boundingBox())!
  await page.mouse.move(grip.x + grip.width / 2, grip.y + grip.height / 2)
  await page.mouse.down()
  await page.mouse.move(grip.x + 70, grip.y + grip.height / 2)
  await page.mouse.up()
  expect((await page.locator('.pane--editor').boundingBox())!.width).toBeGreaterThan(before!.width + 60)
  await page.keyboard.press('Control+k')
  await expect(page.getByRole('textbox', { name: 'Search commands', exact: true })).toBeFocused()
  for (let i = 0; i < 30; i++) await page.keyboard.press('Tab')
  expect(await page.evaluate(() => Boolean(document.activeElement?.closest('dialog[open]')))).toBe(true)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Command palette', exact: true }).click()
  await page.getByRole('textbox', { name: 'Search commands', exact: true }).fill('Insert: Heading 2')
  await page.keyboard.press('Enter')
  await expect(page.locator('.cm-content')).toBeFocused()
  await page.getByRole('button', { name: 'Toggle focus mode', exact: true }).click()
  await expect(page.locator('.pane--preview')).toBeHidden()
  await page.keyboard.press('Escape')
  await expect(page.locator('.pane--preview')).toBeVisible()
  await page.getByRole('button', { name: 'Typewriter mode', exact: true }).click()
  await page.locator('.cm-content').fill('# Focused writing')
  await expect(page.locator('.markdown-body h1')).toHaveText('Focused writing')
})

test('mobile outline, preview, assets, and language controls remain reachable', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.locator('.cm-editor')).toBeVisible()
  await page.getByRole('button', { name: 'Document outline', exact: true }).click()
  await expect(page.locator('.outline-panel')).toBeVisible()
  await page.locator('.outline-panel nav button').first().click()
  await expect(page.locator('.outline-panel')).toBeHidden()
  await page.getByRole('tab', { name: 'Preview', exact: true }).click()
  await expect(page.locator('.markdown-body h1')).toBeVisible()
  await page.getByRole('button', { name: 'Manage local assets', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Local assets', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Close local assets', exact: true }).click()
  await page.getByRole('button', { name: 'Switch to Traditional Chinese', exact: true }).click()
  await expect(page.getByRole('tab', { name: '預覽', exact: true })).toBeVisible()
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.setViewportSize({ width: 812, height: 375 })
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
